"""add column

Revision ID: 23afac575bf9
Revises: 07b8996f3adc
Create Date: 2023-03-05 20:55:43.520657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23afac575bf9'
down_revision = '07b8996f3adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_clickers', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_clickers', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
